name: embench_man
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r

dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - asttokens
  - attrs
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - colorama
  - comm
  - cuda-version=12.6
  - curl
  - cycler
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - expat
  - ffmpeg
  - freetype
  - git-lfs
  - gitdb
  - gitpython
  - importlib-metadata
  - ipykernel
  - ipython
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - keyutils
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libcblas
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libgcc
  - libgcc-ng
  - libgfortran
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libiconv
  - liblapack
  - libllvm14
  - libnghttp2
  - libnsl
  - libopenblas
  - libpng
  - libsodium
  - libsqlite
  - libssh2
  - libstdcxx
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libuv
  - libwebp-base
  - libxcb
  - libxcrypt
  - libzlib
  - llvmlite
  - matplotlib-inline
  - nccl
  - ncurses
  - nest-asyncio
  - numba
  - numpy
  - olefile
  - openjpeg
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pygments
  - pyparsing
  - python=3.10
  - python-dateutil
  - python_abi
  - pyzmq
  - quaternion
  - readline
  - rhash
  - setuptools
  - six
  - smmap
  - stack_data
  - tk
  - tornado
  - tqdm
  - traitlets
  - typing_extensions
  - wcwidth
  - wheel
  - x264
  - xorg-libx11
  - xorg-libxau
  - xorg-libxcursor
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxinerama
  - xorg-libxrandr
  - xorg-libxrender
  - xorg-xorgproto
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd